### ISSUE TITLE
presentable image transition must happen only after acquire

### ISSUE THREAD

**Issue by ratchetfreak** [discoloda/Helix#1]
https://github.com/discoloda/Helix/blob/545cfb4c654f49e1413ca593864af0a5912687f1/window.c#L110

You are only allowed to transition the images after you have acquired it. 

So you either need to track which image you have already acquired at least once. Or always transition from undefined (which is always valid) in [hxWindowBeginFrame](https://github.com/discoloda/Helix/blob/545cfb4c654f49e1413ca593864af0a5912687f1/window.c#L148).

**Comment by discoloda** [comment]
I found no documentation that supports this issue. but it does make the implementation slightly cleaner to delay setting layout until the frame is being prepared to be rendered to.

**Comment by ratchetfreak** [comment]
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain

> Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. This includes transitioning the image layout and rendering commands.
